/**
 * Weather Plugin GraphQL Operations — TypedDocumentNode operations for UI components.
 *
 * All queries used by the weather plugin's UI are defined here.
 * Types are auto-generated by graphql-codegen from the schema.graphql.
 *
 * Run `pnpm codegen` after schema changes to regenerate types.
 *
 * @module plugin-weather/client/operations
 */

import { graphql } from './generated/gql';

// ─────────────────────────────────────────────────────────────────────────────
// Forecast Query
// ─────────────────────────────────────────────────────────────────────────────

export const GET_WEATHER_FORECAST = graphql(`
  query GetWeatherForecast($latitude: Float!, $longitude: Float!, $units: String!) {
    weatherForecast(latitude: $latitude, longitude: $longitude, units: $units) {
      id
      date
      dayName
      high
      low
      condition
      icon
      precipitation
      hourly {
        hour
        temp
        condition
        icon
        precipitation
        humidity
        wind
      }
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Geocoding Search Query
// ─────────────────────────────────────────────────────────────────────────────

export const SEARCH_WEATHER_LOCATIONS = graphql(`
  query SearchWeatherLocations($query: String!) {
    weatherGeocodingSearch(query: $query) {
      id
      name
      country
      admin1
      latitude
      longitude
    }
  }
`);
